Repository Group-16-COSC-310/grocery-chat-bot, pull requests merged in 2022-03, with the labels that each got.

#22 Modify mainbot
  app/bot.py
  app/concerns/other_concern.py
Labels: enhancement

#21 Added refund and exchange handlers
  app/concerns/other_concern.py
Labels: enhancement

#20 Add travis config file
  .travis.yml
  dialogflow_key.json
  dialogflow_key.json.enc
Labels: enhancement

#16 Added nutrition subtopic to allow nutrition fact-related queries
  app/database.py
  app/error.py
  app/products/base_handler.py
  app/products/database.py
  app/products/product_info.py
  app/products/store_info.py
  test/test_database.py
  test/test_product_info.py
  test/test_store_info.py
Labels: enhancement

#25 New implementation from Assignment 3
  .travis.yml
  app/bot.py
  app/concerns/README.md
  app/concerns/other_concern.py
  app/database.py
  app/error.py
  app/products/base_handler.py
  app/products/database.py
  app/products/product_info.py
  app/products/store_info.py
  dialogflow_key.json
  dialogflow_key.json.enc
  main.py
  pytest.ini
  test/test_database.py
  test/test_detect_intents.py
  test/test_product_info.py
  test/test_store_info.py
Labels: enhancement

#17 Update README.md
  README.md
  app/greetings/README.md
Labels: documentation

#27 Fix the sentiment bugs
  app/bot.py
  app/concerns/other_concern.py
  app/greetings/README.md
Labels: bug

#28 Docs
  README.md
  snippets/5responses.PNG
  snippets/entity.PNG
  snippets/mistakes.PNG
  snippets/sentiment.PNG
  snippets/subtopic.PNG
  snippets/synonym.PNG
Labels: documentation

#29 Assignment 3 complete implementation and documentation
  .travis.yml
  README.md
  app/bot.py
  app/concerns/README.md
  app/concerns/other_concern.py
  app/database.py
  app/error.py
  app/greetings/README.md
  app/products/base_handler.py
  app/products/database.py
  app/products/product_info.py
  app/products/store_info.py
  dialogflow_key.json
  dialogflow_key.json.enc
  main.py
  pytest.ini
  snippets/5responses.PNG
  snippets/entity.PNG
  snippets/mistakes.PNG
  snippets/sentiment.PNG
  snippets/subtopic.PNG
  snippets/synonym.PNG
  test/test_database.py
  test/test_detect_intents.py
  test/test_product_info.py
  test/test_store_info.py
Labels: documentation, enhancement
